### ISSUE TITLE
I don't get it. 

### ISSUE THREAD

**Issue by klausbreyer** [jerguslejko/zsh-symfony-completion#3]
First of all: Thanks for doing this! Waited for this a long time. 

But I don't get it. 

I installed it, but when I try the auto completion nothing happens. There are only filenames of the folder. 

![screen shot 2017-10-18 at 11 53 03](https://user-images.githubusercontent.com/32771/31712396-377c3ccc-b3fb-11e7-8e9a-988e0d5af511.png)

Maybe I am doing something wrong or maybe you can write something about the scope of the plugin.

**Comment by jerguslejko** [comment]
Hey Klaus! 

You need to specify a list of tools that you want to turn on the autocompletion for. Put the code below into your `.zshrc`. Also, ensure that you insert it **before** `source $ZSH/oh-my-zsh.sh`.

```zsh
export SYMFONY_CONSOLE_TOOLS="bin/console composer"
```

See the [readme.md](https://github.com/jerguslejko/zsh-symfony-completion/blob/master/README.md) for detailed instructions.

Let me know, if you managed to get it to work :)

**Comment by klausbreyer** [comment]
hi, this is a bit embarrassing. I totally forgot that I was in a vagrant environment. I had however the plugin in the host machine installed. haha. Will now try it the right way.
